services:
  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - "8080:8080"
    user: root
    privileged: true
    restart: unless-stopped
    volumes:
      - ./jenkins_home:/var/jenkins_home/
